definitions: 
  steps: 
    - step: &deploy-prod
        name: Deploy to production environment
        # trigger: manual
        image: node:20.18
        script: 
          - npm pkg delete scripts.prepare
          - npm install --production
          - mkdir -p portfolio-v2/nodejs/node16
          - cp -r node_modules portfolio-v2/nodejs/node16/
          - npm install -g typescript
          - npm install -g serverless
          - npm install serverless-offline
          # Setup AWS profile
          - mkdir -p ~/.aws
          - echo -e "[default]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
          - echo -e "source_profile = default" > ~/.aws/config
          - export AWS_SDK_LOAD_CONFIG=1
          # Deploy
          - sls deploy --verbose

pipelines: 
  default: 
    # - step: *build

  branches: 
    master:
      - step: *deploy-prod